### ISSUE TITLE
installation issue

### ISSUE THREAD

**Issue by macmanes** [camillescott/dammit#18]
on Ubuntu 14.04

```
$ sudo pip install dammit
Downloading/unpacking dammit
  Downloading dammit-0.0.6.tar.gz (64kB): 64kB downloaded
  Running setup.py (path:/tmp/pip_build_root/dammit/setup.py) egg_info for package dammit

    warning: no files found matching '*.h' under directory 'dammit'
Requirement already satisfied (use --upgrade to upgrade): khmer in /usr/local/lib/python2.7/dist-packages/khmer-2.0_rc3_66.g94d679f-py2.7-linux-x86_64.egg (from dammit)
Requirement already satisfied (use --upgrade to upgrade): nose in /usr/lib/python2.7/dist-packages (from dammit)
Downloading/unpacking doit (from dammit)
  Downloading doit-0.29.0.tar.gz (222kB): 222kB downloaded
  Running setup.py (path:/tmp/pip_build_root/doit/setup.py) egg_info for package doit

Downloading/unpacking pandas (from dammit)
  Downloading pandas-0.17.0.tar.gz (6.5MB): 6.5MB downloaded
  Running setup.py (path:/tmp/pip_build_root/pandas/setup.py) egg_info for package pandas

    warning: no files found matching 'README.rst'
    no previously-included directories found matching 'doc/build'
    warning: no directories found matching 'examples'
    warning: no previously-included files matching '*.so' found anywhere in distribution
    warning: no previously-included files matching '*.pyd' found anywhere in distribution
    warning: no previously-included files matching '*.pyc' found anywhere in distribution
    warning: no previously-included files matching '*~' found anywhere in distribution
    warning: no previously-included files matching '#*' found anywhere in distribution
    warning: no previously-included files matching '.git*' found anywhere in distribution
    warning: no previously-included files matching '.DS_Store' found anywhere in distribution
    warning: no previously-included files matching '*.png' found anywhere in distribution
Downloading/unpacking nose-capturestderr (from dammit)
  Downloading nose-capturestderr-1.0.tar.gz
  Running setup.py (path:/tmp/pip_build_root/nose-capturestderr/setup.py) egg_info for package nose-capturestderr

Requirement already satisfied (use --upgrade to upgrade): screed>=0.9 in /usr/local/lib/python2.7/dist-packages/screed-0.9-py2.7.egg (from khmer->dammit)
Requirement already satisfied (use --upgrade to upgrade): bz2file in /usr/local/lib/python2.7/dist-packages/bz2file-0.98-py2.7.egg (from khmer->dammit)
Requirement already satisfied (use --upgrade to upgrade): six in /usr/lib/python2.7/dist-packages (from doit->dammit)
Downloading/unpacking cloudpickle (from doit->dammit)
  Downloading cloudpickle-0.1.1-py2.py3-none-any.whl
Cleaning up...
Exception:
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/pip/basecommand.py", line 122, in main
    status = self.run(options, args)
  File "/usr/lib/python2.7/dist-packages/pip/commands/install.py", line 278, in run
    requirement_set.prepare_files(finder, force_root_egg_info=self.bundle, bundle=self.bundle)
  File "/usr/lib/python2.7/dist-packages/pip/req.py", line 1260, in prepare_files
    )[0]
IndexError: list index out of range
```

here is some of the log file:

```
...Downloading/unpacking nose-capturestderr (from dammit)
  Getting page https://pypi.python.org/simple/nose-capturestderr/
  URLs to search for versions for nose-capturestderr (from dammit):
  * https://pypi.python.org/simple/nose-capturestderr/
  Analyzing links from page https://pypi.python.org/simple/nose-capturestderr/
    Skipping link https://pypi.python.org/packages/2.7/n/nose-capturestderr/nose_capturestderr-1.0-py2.7.egg#md5=eeaffc84d0ccdb887f45724fa130014b (from https://pypi.python.org/simple/nose-capturestderr/); unknown archive format: .egg
    Found link https://pypi.python.org/packages/source/n/nose-capturestderr/nose-capturestderr-1.0.tar.gz#md5=498707ee990533b77e3ffb0265e6802b (from https://pypi.python.org/simple/nose-capturestderr/), version: 1.0
  Downloading nose-capturestderr-1.0.tar.gz
  Downloading from URL https://pypi.python.org/packages/source/n/nose-capturestderr/nose-capturestderr-1.0.tar.gz#md5=498707ee990533b77e3ffb0265e6802b (from https://pypi.python.org/simple/nose-capturestderr/)
  Running setup.py (path:/tmp/pip_build_root/nose-capturestderr/setup.py) egg_info for package nose-capturestderr
    running egg_info
    creating pip-egg-info/nose_capturestderr.egg-info
    writing requirements to pip-egg-info/nose_capturestderr.egg-info/requires.txt
    writing pip-egg-info/nose_capturestderr.egg-info/PKG-INFO
    writing top-level names to pip-egg-info/nose_capturestderr.egg-info/top_level.txt
    writing dependency_links to pip-egg-info/nose_capturestderr.egg-info/dependency_links.txt
    writing entry points to pip-egg-info/nose_capturestderr.egg-info/entry_points.txt
    writing manifest file 'pip-egg-info/nose_capturestderr.egg-info/SOURCES.txt'
    warning: manifest_maker: standard file '-c' not found

    reading manifest file 'pip-egg-info/nose_capturestderr.egg-info/SOURCES.txt'
    writing manifest file 'pip-egg-info/nose_capturestderr.egg-info/SOURCES.txt'
  Source in /tmp/pip_build_root/nose-capturestderr has version 1.0, which satisfies requirement nose-capturestderr (from dammit)
Requirement already satisfied (use --upgrade to upgrade): screed>=0.9 in /usr/local/lib/python2.7/dist-packages/screed-0.9-py2.7.egg (from khmer->dammit)
  skipping extra tests
Requirement already satisfied (use --upgrade to upgrade): bz2file in /usr/local/lib/python2.7/dist-packages/bz2file-0.98-py2.7.egg (from khmer->dammit)
Requirement already satisfied (use --upgrade to upgrade): six in /usr/lib/python2.7/dist-packages (from doit->dammit)
Downloading/unpacking cloudpickle (from doit->dammit)
  Getting page https://pypi.python.org/simple/cloudpickle/
  URLs to search for versions for cloudpickle (from doit->dammit):
  * https://pypi.python.org/simple/cloudpickle/
  Analyzing links from page https://pypi.python.org/simple/cloudpickle/
    Found link https://pypi.python.org/packages/2.7/c/cloudpickle/cloudpickle-0.1.1-py2.py3-none-any.whl#md5=9c1a3dc7f11b3aadf67d8ca6394b4d2e (from https://pypi.python.org/simple/cloudpickle/), version: 0.1.1
    Found link https://pypi.python.org/packages/py2.py3/c/cloudpickle/cloudpickle-0.1.0-py2.py3-none-any.whl#md5=6e638fa79eeac22dc1fd120e6454436b (from https://pypi.python.org/simple/cloudpickle/), version: 0.1.0
    Found link https://pypi.python.org/packages/source/c/cloudpickle/cloudpickle-0.1.0.tar.gz#md5=8a90c85090ccfa9e378076b00393c681 (from https://pypi.python.org/simple/cloudpickle/), version: 0.1.0
    Found link https://pypi.python.org/packages/source/c/cloudpickle/cloudpickle-0.1.1.tar.gz#md5=47376a2fa209283b5e6d05b36eecdb5a (from https://pypi.python.org/simple/cloudpickle/), version: 0.1.1
  Using version 0.1.1 (newest of versions: 0.1.1, 0.1.1, 0.1.0, 0.1.0)
  Downloading cloudpickle-0.1.1-py2.py3-none-any.whl
  Downloading from URL https://pypi.python.org/packages/2.7/c/cloudpickle/cloudpickle-0.1.1-py2.py3-none-any.whl#md5=9c1a3dc7f11b3aadf67d8ca6394b4d2e (from https://pypi.python.org/simple/cloudpickle/)
Cleaning up...
  Removing temporary dir /tmp/pip_build_root...
Exception:
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/pip/basecommand.py", line 122, in main
    status = self.run(options, args)
  File "/usr/lib/python2.7/dist-packages/pip/commands/install.py", line 278, in run
    requirement_set.prepare_files(finder, force_root_egg_info=self.bundle, bundle=self.bundle)
  File "/usr/lib/python2.7/dist-packages/pip/req.py", line 1260, in prepare_files
    )[0]
IndexError: list index out of range
```

**Comment by macmanes** [comment]
of note, https://github.com/camillescott/dammit/issues/9 seems to work. Why not put those instructions in the README or some other (more) visible document?

**Comment by macmanes** [comment]
great, thanks!

**Comment by macmanes** [comment]
I think a few dependencies have been added?

```
sudo pip install ficus
```

and 

```
sudo apt-get install python-sklearn
```
