### ISSUE TITLE
Error: sqlite3 unable to open database file

### ISSUE THREAD

**Issue by blasks** [camillescott/dammit#183]
I've had a number of troubles getting dammit installed and working on my MacOS environment. I have miniconda3 installed and download dammit into a new environment using the following:

```
conda create -n dammit python=3.6
conda activate dammit
conda install dammit
```

With this, conda takes several minutes to solve the environment. Once everything is downloaded and installed, `which busco` returns nothing despite conda saying that it was downloaded and installed. Then when I try to run `dammit databases --full --database-dir <directory/path> --busco-group protists --install` I get the following error:

```
Traceback (most recent call last):
  File "/opt/miniconda3/envs/dammit/lib/python3.6/site-packages/doit/doit_cmd.py", line 177, in run
    return command.parse_execute(args)
  File "/opt/miniconda3/envs/dammit/lib/python3.6/site-packages/doit/cmd_base.py", line 127, in parse_execute
    return self.execute(params, args)
  File "/opt/miniconda3/envs/dammit/lib/python3.6/site-packages/doit/cmd_base.py", line 406, in execute
    db_class, params['dep_file'], checker_cls)
  File "/opt/miniconda3/envs/dammit/lib/python3.6/site-packages/doit/dependency.py", line 475, in __init__
    self.backend = db_class(backend_name)
  File "/opt/miniconda3/envs/dammit/lib/python3.6/site-packages/doit/dependency.py", line 236, in __init__
    self._conn = self._sqlite3(self.name)
  File "/opt/miniconda3/envs/dammit/lib/python3.6/site-packages/doit/dependency.py", line 261, in _sqlite3
    isolation_level='DEFERRED')
sqlite3.OperationalError: unable to open database file
```

I checked and sqlite3 is properly installed in the environment. I've been able to run at least the non-busco steps of the pipeline previously, but now I can't even do that because of this error.

**Comment by schippmeister** [comment]
Same problem for me, though I am using python 3.7

**Comment by camillescott** [comment]
Sorry for missing this issue originally. dammit v1.x is not compatible with MacOS due to issues with pinned dependencies. v2 will likely work on MacOS, but the compatibility is a work in progress.

**Comment by mptrsen** [comment]
Hi Camille! I'm having the same issue with v1.2, but on Linux. Same installation procedure.

**Comment by taylorreiter** [comment]
I also received this error on linux, but only when I tried to specify an output directory for the database. If I let it download the databases to the default path, no error occurs.
