### ISSUE TITLE
TypeError: an integer is required (got type bytes)

### ISSUE THREAD

**Issue by jtoy7** [camillescott/dammit#227]
I just tried to install dammit on a cluster using conda. Per the bioconda site, I ran:

`conda create -n dammit python=3  
source activate dammit

conda config --add channels conda-forge 
conda config --add channels bioconda 

conda install dammit`

The installation seemed to run successfully, as there were no error messages. However, when I try running `dammit databases` or any other dammit command, I get the following errors:

Traceback (most recent call last):
  File "/hb/groups/bernardi_lab/programs/miniconda3/envs/dammit/bin/dammit", line 5, in <module>
    from dammit import app
  File "/hb/groups/bernardi_lab/programs/miniconda3/envs/dammit/lib/python3.8/site-packages/dammit/app.py", line 13, in <module>
	from dammit import annotate
  File "/hb/groups/bernardi_lab/programs/miniconda3/envs/dammit/lib/python3.8/site-packages/dammit/annotate.py", line 13, in <module>
	from shmlast.app import CRBL
  File "/hb/groups/bernardi_lab/programs/miniconda3/envs/dammit/lib/python3.8/site-packages/shmlast/app.py", line 3, in <module>
	from doit.tools import run_once, create_folder
  File "/hb/groups/bernardi_lab/programs/miniconda3/envs/dammit/lib/python3.8/site-packages/doit/__init__.py", line 33, in <module>
	from doit.doit_cmd import get_var
  File "/hb/groups/bernardi_lab/programs/miniconda3/envs/dammit/lib/python3.8/site-packages/doit/doit_cmd.py", line 15, in <module>
	from .cmd_run import Run
  File "/hb/groups/bernardi_lab/programs/miniconda3/envs/dammit/lib/python3.8/site-packages/doit/cmd_run.py", line 9, in <module>
	from .runner import Runner, MRunner, MThreadRunner
  File "/hb/groups/bernardi_lab/programs/miniconda3/envs/dammit/lib/python3.8/site-packages/doit/runner.py", line 8, in <module>
	import cloudpickle
  File "/hb/software/apps/python/gnu-3.6.2/lib/python3.6/site-packages/cloudpickle/__init__.py", line 3, in <module>
	from cloudpickle.cloudpickle import *
  File "/hb/software/apps/python/gnu-3.6.2/lib/python3.6/site-packages/cloudpickle/cloudpickle.py", line 151, in <module>
    _cell_set_template_code = _make_cell_set_template_code()
  File "/hb/software/apps/python/gnu-3.6.2/lib/python3.6/site-packages/cloudpickle/cloudpickle.py", line 132, in _make_cell_set_template_code
	return types.CodeType(
  TypeError: an integer is required (got type bytes)

Other than seeing that a bunch of python scripts aren't functioning, I can't tell what's going wrong. Agian, it seemed to install just fine, so I feel like there must be some other issue? Has this happened to anyone else?

**Comment by jtoy7** [comment]
So it looks like it was an issue with the python version. I downgraded from python 3.8 to 3.6 and it seems to have resolved the issue. However, now, when I try to run any `dammit databases` command, the program stalls out with a forever blinking cursor after printing:

> dammit 
>   a tool for easy de novo transcriptome annotation
> by Camille Scott
> **v1.2**, 2018
>   submodule: databases

So close, but yet so far...any advice in getting this working is appreciated!

**Comment by jtoy7** [comment]
Here is the current status of the log file if that helps
[dammit-all.log](https://github.com/dib-lab/dammit/files/6247057/dammit-all.log)
