### ISSUE TITLE
No symbol dbm_open found in library libdb-6.2.so

### ISSUE THREAD

**Issue by pmoulos** [camillescott/dammit#230]
Hi!

I just finished installing `dammit` following all the instructions. However, when trying to install databases (quick mode):

`dammit databases --install --quick`

I get

```
Traceback (most recent call last):
  File "/home/moulos/anaconda3/envs/dammit-env/lib_pypy/_dbm.py", line 126, in _init_func
    func = getattr(lib, '__db_ndbm_' + name)
  File "/home/moulos/anaconda3/envs/dammit-env/lib-python/3/ctypes/__init__.py", line 382, in __getattr__
    func = self.__getitem__(name)
  File "/home/moulos/anaconda3/envs/dammit-env/lib-python/3/ctypes/__init__.py", line 387, in __getitem__
    func = self._FuncPtr((name_or_ordinal, self))
  File "/home/moulos/anaconda3/envs/dammit-env/lib_pypy/_ctypes/function.py", line 255, in __init__
    ptr = self._getfuncptr([], ctypes.c_int)
  File "/home/moulos/anaconda3/envs/dammit-env/lib_pypy/_ctypes/function.py", line 442, in _getfuncptr
    self._ptr = cdll.getfunc(self.name, ffi_argtypes, ffi_restype)
AttributeError: No symbol __db_ndbm_open found in library /home/moulos/anaconda3/envs/dammit-env/lib/libdb-6.2.so

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/moulos/anaconda3/envs/dammit-env/bin/dammit", line 5, in <module>
    from dammit import app
  File "/home/moulos/anaconda3/envs/dammit-env/site-packages/dammit/app.py", line 13, in <module>
    from dammit import annotate
  File "/home/moulos/anaconda3/envs/dammit-env/site-packages/dammit/annotate.py", line 13, in <module>
    from shmlast.app import CRBL
  File "/home/moulos/anaconda3/envs/dammit-env/site-packages/shmlast/app.py", line 3, in <module>
    from doit.tools import run_once, create_folder
  File "/home/moulos/anaconda3/envs/dammit-env/site-packages/doit/__init__.py", line 31, in <module>
    from doit import loader
  File "/home/moulos/anaconda3/envs/dammit-env/site-packages/doit/loader.py", line 10, in <module>
    from .task import DelayedLoader, Task, dict_to_task
  File "/home/moulos/anaconda3/envs/dammit-env/site-packages/doit/task.py", line 14, in <module>
    from .dependency import UptodateCalculator
  File "/home/moulos/anaconda3/envs/dammit-env/site-packages/doit/dependency.py", line 9, in <module>
    from dbm import dumb
  File "/home/moulos/anaconda3/envs/dammit-env/lib-python/3/dbm/__init__.py", line 48, in <module>
    from dbm import ndbm
  File "/home/moulos/anaconda3/envs/dammit-env/lib-python/3/dbm/ndbm.py", line 3, in <module>
    from _dbm import *
  File "/home/moulos/anaconda3/envs/dammit-env/lib_pypy/_dbm.py", line 155, in <module>
    _init_func('open', (c_char_p, c_int, c_int), restype=c_void_p)
  File "/home/moulos/anaconda3/envs/dammit-env/lib_pypy/_dbm.py", line 129, in _init_func
    func = getattr(lib, 'dbm_' + name)
  File "/home/moulos/anaconda3/envs/dammit-env/lib-python/3/ctypes/__init__.py", line 382, in __getattr__
    func = self.__getitem__(name)
  File "/home/moulos/anaconda3/envs/dammit-env/lib-python/3/ctypes/__init__.py", line 387, in __getitem__
    func = self._FuncPtr((name_or_ordinal, self))
  File "/home/moulos/anaconda3/envs/dammit-env/lib_pypy/_ctypes/function.py", line 255, in __init__
    ptr = self._getfuncptr([], ctypes.c_int)
  File "/home/moulos/anaconda3/envs/dammit-env/lib_pypy/_ctypes/function.py", line 442, in _getfuncptr
    self._ptr = cdll.getfunc(self.name, ffi_argtypes, ffi_restype)
AttributeError: No symbol dbm_open found in library /home/moulos/anaconda3/envs/dammit-env/lib/libdb-6.2.so
```

Thank you in advance

**Comment by josruirod** [comment]
Exactly the same problem on a new installation over here. Hope it can be resolved or you found some solution. Thanks
