### ISSUE TITLE
unable to install databases

### ISSUE THREAD

**Issue by peter0k** [camillescott/dammit#243]
Hi,

I installed dammit dev version (pip install git+https://github.com/camillescott/dammit.git).

If I try to install a database ( dammit databases --install --busco-group eukaryota) I'm getting following error:

\#\# submodule: databases
Traceback (most recent call last):
  File "/home/peter/.local/bin/dammit", line 9, in <module>
    sys.exit(app.DammitApp(arg_src=sys.argv[1:]).run())
  File "/home/peter/.local/lib/python3.10/site-packages/dammit/app.py", line 45, in run
    return self.args.func()
  File "/home/peter/.local/lib/python3.10/site-packages/dammit/app.py", line 278, in handle_databases
    handler = databases.get_handler(self.config_d)
  File "/home/peter/.local/lib/python3.10/site-packages/dammit/databases.py", line 41, in get_handler
    handler = TaskHandler(config['database_dir'],
  File "/home/peter/.local/lib/python3.10/site-packages/dammit/handler.py", line 49, in \_\_init\_\_
    super(TaskHandler, self).\_\_init\_\_()
  File "/home/peter/.local/lib/python3.10/site-packages/doit/cmd_base.py", line 289, in \_\_init\_\_
    raise NotImplementedError(
NotImplementedError: doit.cmd_base.py:TaskLoader was removed on 0.36.0, use TaskLoader2 instead

Yesterday I tried to install dammit via conda and obtained same error.

If somebody has an idea: Thank you!

**Comment by Anto007** [comment]
@peter0k, I ran into the same issue but fixed it by adding `doit=0.35.0 `to my conda environment. My .yml file at the time of building the conda dammit environment looked like the below. Hope this helps

```
name: null

channels: 
    - conda-forge
    - defaults
    - bioconda
 
dependencies:
    - python=3
    - doit=0.35.0
    - dammit
```

**Comment by Anto007** [comment]
But subsequently, I ran into the same error as [Issue 241](https://github.com/dib-lab/dammit/issues/241) Trying to figure out now a way out of this new error :-(

**Comment by Anto007** [comment]
Seems like I might need to give up on this. Most required db files were downloaded (my command-line after activating the conda environment- `dammit databases --install --database-dir /data/conda_dammit_env/db --full --busco-group eukaryota`) excepting the OrthoDB one (as the older version files that dammit requires isn't available on OrthoDB anymore). I got around the OrthoDB download issue by downloading an old version of the db files that was archived at [Zenodo](https://zenodo.org/api/files/773602b2-e239-4489-8f97-cebb99f36a81/dbs.tar.gz) by a kind user in this [thread](https://github.com/dib-lab/dammit/issues/229). Unzipped this downloaded db and I then replaced busco2db (containing busco fungal lineage) in this dir with the eukaryota lineage containing busco2db that I had downloaded at the initial step. I then set the database path by entering `export DAMMIT_DB_DIR=/data/conda_dammit_env/old_db/dbs` and ran the command ` dammit annotate thin2_rnaspades_assembly.fasta --busco-group eukaryota --n_threads 32`. I encountered yet another error `TypeError: lastal_task() got an unexpected keyword argument 'pbs'` which I fixed by commenting out the line starting with `pbs` in /data/conda_dammit_env/lib/python3.8/site-packages/dammit/annotate.py (as suggested in this [thread](https://github.com/dib-lab/dammit/issues/203)). I now reran the above damit annotate command-line and I have encountered a new `strand` error at the `hmmscan-gff3:thin2_rnaspades_assembly.fasta.x.pfam-A.gff3` step- 
```
File "pandas/_libs/hashtable_class_helper.pxi", line 4562, in pandas._libs.hashtable.PyObjectHashTable.get_item
KeyError: 'strand'
`
```
DAMM IT!!!! :-(
