### ISSUE TITLE
numexpr needed

### ISSUE THREAD

**Issue by macmanes** [camillescott/dammit#37]
using dammit v. 0.2.0

```
dammit annotate Harmonia.v1.0.0.fasta --busco-group arthropoda --full -o harm2 --n_threads 32 --database-dir /mnt/dammit/
```

```
transdecoder is finished.  See output files Harmonia.v1.0.0.fasta.transdecoder.*


          [ ] cmscan:Harmonia.v1.0.0.fasta.x.Rfam.cm

          [ ] lastal:Harmonia.v1.0.0.fasta.x.orthodb.maf

          [ ] maf_best_hits:Harmonia.v1.0.0.fasta.x.orthodb.maf-
          Harmonia.v1.0.0.fasta.x.orthodb.maf.best.csv

          [ ] maf-gff3:Harmonia.v1.0.0.fasta.x.orthodb.maf.gff3

          [ ] hmmscan-gff3:longest_orfs.pep.pfam.tbl.gff3

          [ ] cmscan-gff3:Harmonia.v1.0.0.fasta.rfam.tbl.gff3

          [ ] gff3-merge:Harmonia.v1.0.0.fasta.dammit.gff3

          [ ] fasta-annotate:Harmonia.v1.0.0.fasta.dammit.fasta

Some tasks failed![dammit.annotate:ERROR]
TaskError - taskid:fasta-annotate:Harmonia.v1.0.0.fasta.dammit.fasta[dammit.annotate:ERROR]
PythonAction Error
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/doit/action.py", line 383, in execute
    returned_value = self.py_callable(*self.args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/dammit/tasks.py", line 593, in annotate_fasta
    df = annotations.query('seqid == "{0}"'.format(record.name))
  File "/usr/local/lib/python2.7/dist-packages/pandas/core/frame.py", line 2107, in query
    res = self.eval(expr, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/pandas/core/frame.py", line 2159, in eval
    return _eval(expr, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/pandas/computation/eval.py", line 218, in eval
    _check_engine(engine)
  File "/usr/local/lib/python2.7/dist-packages/pandas/computation/eval.py", line 40, in _check_engine
    raise ImportError("'numexpr' not found. Cannot use "
ImportError: 'numexpr' not found. Cannot use engine='numexpr' for query/eval if 'numexpr' is not installed
[dammit.annotate:ERROR]
```

Fixed by `sudo pip install numexpr`

restarted:

```
dammit annotate Harmonia.v1.0.0.fasta --busco-group arthropoda --full -o harm2 --n_threads 32 --database-dir /mnt/dammit/
```

**Comment by camillescott** [comment]
Good catch! I'll update the requirements.
