### ISSUE TITLE
error with custom database

### ISSUE THREAD

**Issue by macmanes** [camillescott/dammit#56]
```
dammit annotate ../assembly/RockDove.HPG.v1.0.2.fasta \
--user-databases /mnt/data3/macmanes/dammit_databases/tcdb.fasta /mnt/data3/macmanes/dammit_databases/Gallus_gallus.Galgal4.ncrna.fa \
--busco-group vertebrata --n_threads 15 --full \
--database-dir /mnt/data3/macmanes/dammit_databases/

...
          [ ] crbb-gff3:RockDove.HPG.v1.0.2.fasta.x.tcdb.fasta.crbb.tsv.gff3

Some tasks failed![dammit.annotate:ERROR]
TaskError - taskid:crbb-gff3:RockDove.HPG.v1.0.2.fasta.x.Gallus_gallus.Galgal4.ncrna.fa.crbb.tsv.gff3[dammit.annotate:ERROR]
PythonAction Error
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/doit/action.py", line 383, in execute
    returned_value = self.py_callable(*self.args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/dammit/tasks.py", line 539, in cmd
    remap=True):
  File "/usr/local/lib/python2.7/dist-packages/dammit/parsers.py", line 284, in crb_to_df_iter
    remap_blast(group)
  File "/usr/local/lib/python2.7/dist-packages/dammit/blast.py", line 68, in remap_blast_coords_df
    df['sstrand'] = coords[coords:,4]
IndexError: invalid slice
[dammit.annotate:ERROR]
Some tasks failed![dammit.annotate:ERROR]
TaskError - taskid:crbb-gff3:RockDove.HPG.v1.0.2.fasta.x.tcdb.fasta.crbb.tsv.gff3[dammit.annotate:ERROR]
PythonAction Error
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/doit/action.py", line 383, in execute
    returned_value = self.py_callable(*self.args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/dammit/tasks.py", line 539, in cmd
    remap=True):
  File "/usr/local/lib/python2.7/dist-packages/dammit/parsers.py", line 284, in crb_to_df_iter
    remap_blast(group)
  File "/usr/local/lib/python2.7/dist-packages/dammit/blast.py", line 68, in remap_blast_coords_df
    df['sstrand'] = coords[coords:,4]
IndexError: invalid slice
[dammit.annotate:ERROR]
Some tasks failed![dammit.annotate:ERROR]
UnmetDependency - taskid:gff3-merge:RockDove.HPG.v1.0.2.fasta.dammit.gff3[dammit.annotate:ERROR]
crbb-gff3:RockDove.HPG.v1.0.2.fasta.x.tcdb.fasta.crbb.tsv.gff3 crbb-gff3:RockDove.HPG.v1.0.2.fasta.x.Gallus_gallus.Galgal4.ncrna.fa.crbb.tsv.gff3
[dammit.annotate:ERROR]
Some tasks failed![dammit.annotate:ERROR]
UnmetDependency - taskid:fasta-annotate:RockDove.HPG.v1.0.2.fasta.dammit.fasta[dammit.annotate:ERROR]
gff3-merge:RockDove.HPG.v1.0.2.fasta.dammit.gff3
[dammit.annotate:ERROR]
```

**Comment by camillescott** [comment]
This was fixed in the most recent release :)
