### ISSUE TITLE
Problems with app.py

### ISSUE THREAD

**Issue by mddawson77** [camillescott/dammit#59]
Hello,

I am trying to run dammit and I keep getting the error messages below, which I have tried to fix with no success. Any suggestions will be helpful! -Molly

```
--- Database results

          All databases prepared!

Traceback (most recent call last):
  File "/usr/local/bin/dammit", line 10, in <module>
    app.DammitApp(arg_src=sys.argv[1:]).run()
  File "/usr/local/lib/python2.7/dist-packages/dammit/app.py", line 31, in run
    self.args.func()
  File "/usr/local/lib/python2.7/dist-packages/dammit/app.py", line 206, in handle_annotate
    annotate.AnnotateHandler(self.args, db_handler.databases).handle()
  File "/usr/local/lib/python2.7/dist-packages/dammit/annotate.py", line 49, in __init__
    self.tasks = list(self.get_tasks())
  File "/usr/local/lib/python2.7/dist-packages/dammit/annotate.py", line 258, in get_tasks
    for task in self.transdecoder_tasks():
  File "/usr/local/lib/python2.7/dist-packages/dammit/annotate.py", line 180, in transdecoder_tasks
    common.CONFIG['settings']['hmmer']['hmmscan'])
  File "/usr/local/lib/python2.7/dist-packages/dammit/tasks.py", line 60, in d_to_t
    ret_dict = task_dict_func(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/dammit/tasks.py", line 438, in get_hmmscan_task
    input_filename])
TypeError: sequence item 0: expected string, NoneType found
```

**Comment by camillescott** [comment]
Could you give me an example of the command you're running, and your current version? This doesn't look like anything I've seen before :)

**Comment by mddawson77** [comment]
Hi Camille!

I am using v0.2.7.1!  

Here is my code:

```
dammit annotate /home/molly/tucoKidney/transrate_v1.0.2/tuco_1/Rcorr_trinity_tucoKidney.Trinity/good.Rcorr_trinity_tucoKidney.Trinity.fasta \
--user-databases /data/dammit_databases/tcdb.fasta  \
--busco-group vertebrata \
--n_threads 12 \
--full \
--database-dir /data/dammit_databases/
```

**Comment by camillescott** [comment]
Thanks! If you're able you should definitely upgrade to the latest version with `pip install -U dammit`. Unfortunately, being a grad student / pressed for time / Not Yet a Wizard means that sometimes I push releases with bugs in them :) The newer version will also be a *lot* faster.

**Comment by mddawson77** [comment]
Up and running smoothly, thank you!
