### ISSUE TITLE
TypeError: sequence item 4: expected string, NoneType found

### ISSUE THREAD

**Issue by jwidmann** [camillescott/dammit#61]
Hi,
I tried running dammit after updating via 
`sudo pip install -U dammit`
with the command 
`dammit annotate TrinityNormalizedTissues.fasta --n_threads 2 --busco-group eukaryota`
and get the following Error message:
`Traceback (most recent call last):
  File "/usr/local/bin/dammit", line 10, in <module>
    app.DammitApp(arg_src=sys.argv[1:]).run()
  File "/usr/local/lib/python2.7/dist-packages/dammit/app.py", line 31, in run
    self.args.func()
  File "/usr/local/lib/python2.7/dist-packages/dammit/app.py", line 212, in handle_annotate
    annotate.AnnotateHandler(self.args, db_handler.databases).handle()
  File "/usr/local/lib/python2.7/dist-packages/dammit/annotate.py", line 49, in __init__
    self.tasks = list(self.get_tasks())
  File "/usr/local/lib/python2.7/dist-packages/dammit/annotate.py", line 261, in get_tasks
    for task in self.transdecoder_tasks():
  File "/usr/local/lib/python2.7/dist-packages/dammit/annotate.py", line 181, in transdecoder_tasks
    n_nodes=self.args.n_nodes)
  File "/usr/local/lib/python2.7/dist-packages/dammit/tasks.py", line 88, in d_to_t
    ret_dict = task_dict_func(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/dammit/tasks.py", line 473, in get_hmmscan_task
    parallel_cmd = parallel_fasta(input_filename, n_threads)
  File "/usr/local/lib/python2.7/dist-packages/dammit/tasks.py", line 56, in parallel_fasta
    return ' '.join(cmd)
TypeError: sequence item 4: expected string, NoneType found
`
The temporary files are called TRINITY_DNxxxxx_cx_gx_ixNone_.temp
How can I solve this?
Greetings

**Comment by jwidmann** [comment]
I'm really sorry, I just forgot to install parallel..
Sorry for stealing your time.

**Comment by camillescott** [comment]
Hi @jwidmann! I'm actually going to reopen this so I can add a check for parallel to the dependency handler. Thanks for filing!

**Comment by camillescott** [comment]
Fixed in 1.0 beta; closing.
