### ISSUE TITLE
Not running UniRef search

### ISSUE THREAD

**Issue by DragonCMD** [camillescott/dammit#71]
[dammit-all.log.txt](https://github.com/camillescott/dammit/files/446469/dammit-all.log.txt)
Hi Camille,

We're having a little trouble with searching the UniRef database.  All dependencies and databases requirements are satisfied, and it seems to run all of the steps successfully until it reaches the the last UniRef search.  I've attached the dammit-all.log as well.  We'd appreciate any help or pointers - thank you!

--- Running annotate!

          Transcriptome file: hybrid_490_clean_trinity.Trinity.fasta

          Output directory:
          /home/victaphanta/hybrid_490_clean_trinity.Trinity.fasta.dammit

          [ ] hybrid_490_clean_trinity.Trinity.fasta

          [ ] transcriptome_stats:hybrid_490_clean_trinity.Trinity.fasta

          [ ] busco:hybrid_490_clean_trinity.Trinity.fasta-vertebrata

          [ ] TransDecoder.LongOrfs:hybrid_490_clean_trinity.Trinity.fasta

          [ ] hmmscan:longest_orfs.pep.x.Pfam-A.hmm

          [ ] remap_hmmer:longest_orfs.pep.pfam.tbl

          [ ] TransDecoder.Predict:hybrid_490_clean_trinity.Trinity.fasta

          [ ] cmscan:hybrid_490_clean_trinity.Trinity.fasta.x.Rfam.cm

          [ ] lastal:hybrid_490_clean_trinity.Trinity.fasta.x.orthodb.maf

          [ ] lastal:hybrid_490_clean_trinity.Trinity.fasta.x.uniref.maf

          [ ] maf_best_hits:hybrid_490_clean_trinity.Trinity.fasta.x.orthodb.maf-
          hybrid_490_clean_trinity.Trinity.fasta.x.orthodb.maf.best.csv

          [ ] maf-gff3:hybrid_490_clean_trinity.Trinity.fasta.x.orthodb.maf.gff3

          [ ] maf_best_hits:hybrid_490_clean_trinity.Trinity.fasta.x.uniref.maf-
          hybrid_490_clean_trinity.Trinity.fasta.x.uniref.maf.best.csv

Some tasks failed![dammit.annotate:ERROR]
TaskError - taskid:maf_best_hits:hybrid_490_clean_trinity.Trinity.fasta.x.uniref.maf-hybrid_490_clean_trinity.Trinity.fasta.x.uniref.maf.best.csv[dammit.annotate:ERROR]
PythonAction Error
Traceback (most recent call last):
  File "/home/victaphanta/.local/lib/python2.7/site-packages/doit/action.py", line 383, in execute
    returned_value = self.py_callable(*self.args, **kwargs)
  File "/home/victaphanta/.local/lib/python2.7/site-packages/dammit/tasks.py", line 343, in cmd
    df = maf.MafParser(maf_fn).read()
  File "/home/victaphanta/.local/lib/python2.7/site-packages/dammit/fileio/maf.py", line 16, in read
    return pd.concat(self, ignore_index=True)
  File "/home/victaphanta/.local/lib/python2.7/site-packages/pandas/tools/merge.py", line 845, in concat
    copy=copy)
  File "/home/victaphanta/.local/lib/python2.7/site-packages/pandas/tools/merge.py", line 878, in __init__
    raise ValueError('No objects to concatenate')
ValueError: No objects to concatenate
[dammit.annotate:ERROR]

**Comment by DragonCMD** [comment]
Hi Camille,

No worries, found the problem and fixed it.  UniRef90 is just quite a large database so my virtual machine was running out of memory and wasn't building the lastdb.  Thanks!

Caroline
