### ISSUE TITLE
dammit on Ubuntu 14.04

### ISSUE THREAD

**Issue by macmanes** [camillescott/dammit#73]
Camille, 

Looks like dammit has issues on ubuntu 14.04 related to not having a new version of glibc.. 

```
gcc --version
gcc (Homebrew gcc 5.3.0) 5.3.0

ldd --version
2.19
```

Installing like this:

```
sudo apt-get update && sudo apt-get -y upgrade && sudo apt-get -y dist-upgrade
sudo apt-get -y install build-essential git python-pip python-numpy python-matplotlib

# Install LinuxBrew and some software

gem install crb-blast
pip install -U setuptools
pip install pandas
pip install dammit

...
Successfully built dammit khmer doit nose-capturestderr ficus screed bz2file pyinotify configparser docutils MarkupSafe
Installing collected packages: bz2file, screed, khmer, cloudpickle, pyinotify, configparser, doit, imagesize, Pygments, snowballstemmer, alabaster, docutils, babel, MarkupSafe, Jinja2, Sphinx, sphinx-rtd-theme, nose, nose-capturestderr, cycler, pyparsing, matplotlib, ficus, numexpr, dammit
Successfully installed Jinja2-2.8 MarkupSafe-0.23 Pygments-2.1.3 Sphinx-1.4.8 alabaster-0.7.9 babel-2.3.4 bz2file-0.98 cloudpickle-0.2.1 configparser-3.5.0 cycler-0.10.0 dammit-0.3 docutils-0.12 doit-0.29.0 ficus-0.3.2 imagesize-0.7.1 khmer-2.0 matplotlib-1.5.3 nose-1.3.4 nose-capturestderr-1.0 numexpr-2.6.1 pyinotify-0.9.6 pyparsing-2.1.10 screed-0.9 snowballstemmer-1.2.1 sphinx-rtd-theme-0.1.9
```

```

$ dammit

Traceback (most recent call last):
  File "/home/linuxbrew/.linuxbrew/bin/dammit", line 4, in <module>
    import dammit
  File "/home/linuxbrew/.linuxbrew/Cellar/python/2.7.12_3/lib/python2.7/site-packages/dammit/__init__.py", line 12, in <module>
    import tasks
  File "/home/linuxbrew/.linuxbrew/Cellar/python/2.7.12_3/lib/python2.7/site-packages/dammit/tasks.py", line 18, in <module>
    from khmer import HLLCounter, ReadParser
  File "/home/linuxbrew/.linuxbrew/Cellar/python/2.7.12_3/lib/python2.7/site-packages/khmer/__init__.py", line 42, in <module>
    from khmer._khmer import Countgraph as _Countgraph
ImportError: /usr/lib/x86_64-linux-gnu/libstdc++.so.6: version `GLIBCXX_3.4.20' not found (required by /home/linuxbrew/.linuxbrew/Cellar/python/2.7.12_3/lib/python2.7/site-packages/khmer/_khmer.so)
```

**Comment by camillescott** [comment]
This seems like a khmer / linuxbrew issue -- does the error happen with the recommended install procedure? You might consider cross-posting to the khmer project as well.

**Comment by camillescott** [comment]
This issue seems to be specific to khmer and linuxbrew; closing for now as third-party.
