### ISSUE TITLE
doit database deadlock

### ISSUE THREAD

**Issue by ljcohen** [camillescott/dammit#75]
khmer_env)ljcohen@c8-22:~/dammit$ dammit annotate A_xenica.Trinity.fixed.fa --user-databases protein.fa --busco-group metazoa --n_threads 4
========================================
dammit! a tool for easy de novo transcriptome annotation
Camille Scott 2015
========================================

~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
submodule: annotate
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

--- Checking PATH for dependencies

          [x] HMMER

          [x] Infernal

          [x] BLAST+

          [x] BUSCO

          [x] TransDecoder

          [x] LAST

          [x] crb-blast

--- Dependency results

          All dependencies satisfied!

--- Checking for database prep (dir: /home/ljcohen/.dammit/databases)

          [x] download_and_gunzip:Pfam-A.hmm

          [x] hmmpress:Pfam-A.hmm

          [x] download_and_gunzip:Rfam.cm

          [x] cmpress:Rfam.cm

          [x] download_and_gunzip:aa_seq_euk.fasta

          [x] lastdb:aa_seq_euk.fasta.db

          [x] download_and_gunzip:ODB8_EukOGs_genes_ALL_levels.txt

          [x] download_and_untar:databases-metazoa

--- Database results

          All databases prepared!

--- Running annotate!

          Transcriptome file: A_xenica.Trinity.fixed.fa

          Output directory: /home/ljcohen/dammit/A_xenica.Trinity.fixed.fa.dammit

          [x] A_xenica.Trinity.fixed.fa

          [x] transcriptome_stats:A_xenica.Trinity.fixed.fa

          [x] busco:A_xenica.Trinity.fixed.fa-metazoa

          [ ] TransDecoder.LongOrfs:A_xenica.Trinity.fixed.fa

          [ ] hmmscan:longest_orfs.pep.x.Pfam-A.hmm

^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^C^CException KeyboardInterrupt in <bound method Popen.__del__ of <subprocess.Popen object at 0x2ac92865dc50>> ignored
Traceback (most recent call last):
  File "/home/ljcohen/anaconda2/envs/khmer_env/lib/python2.7/site-packages/doit/doit_cmd.py", line 168, in run
    return command.parse_execute(args)
  File "/home/ljcohen/anaconda2/envs/khmer_env/lib/python2.7/site-packages/doit/cmd_base.py", line 122, in parse_execute
    return self.execute(params, args)
  File "/home/ljcohen/anaconda2/envs/khmer_env/lib/python2.7/site-packages/doit/cmd_base.py", line 405, in execute
    return self._execute(**exec_params)
  File "/home/ljcohen/anaconda2/envs/khmer_env/lib/python2.7/site-packages/doit/cmd_run.py", line 253, in _execute
    return runner.run_all(self.control.task_dispatcher())
  File "/home/ljcohen/anaconda2/envs/khmer_env/lib/python2.7/site-packages/doit/runner.py", line 252, in run_all
    self.finish()
  File "/home/ljcohen/anaconda2/envs/khmer_env/lib/python2.7/site-packages/doit/runner.py", line 232, in finish
    self.dep_manager.close()
  File "/home/ljcohen/anaconda2/envs/khmer_env/lib/python2.7/site-packages/doit/dependency.py", line 509, in close
    self.backend.dump()
  File "/home/ljcohen/anaconda2/envs/khmer_env/lib/python2.7/site-packages/doit/dependency.py", line 340, in dump
    (task_id, json.dumps(self._cache[task_id])))
OperationalError: database is locked
^C

**Comment by camillescott** [comment]
Still not sure how to fix this or what triggers it; just gonna leave it here now until it can be reproduced.
