### ISSUE TITLE
ValueError at Python: do_crbl_fit_and_filter

### ISSUE THREAD

**Issue by ljcohen** [camillescott/dammit#76]
- [ ] user-database:protein.fa-shmlast-fit_and_filter_crbl_hits: 
    * Python: do_crbl_fit_and_filter
/home/ljcohen/anaconda2/envs/py3.dammit/lib/python3.5/site-packages/shmlast-1.0-py3.5.egg/shmlast/crbl.py:61: RuntimeWarning: invalid value encountered in log10
  df[scaled_col_name] = -np.log10(df[scaled_col_name])
########################################
TaskError - taskid:user-database:protein.fa-shmlast-fit_and_filter_crbl_hits
PythonAction Error
Traceback (most recent call last):
  File "/home/ljcohen/anaconda2/envs/py3.dammit/lib/python3.5/site-packages/doit-0.29.0-py3.5.egg/doit/tools.py", line 223, in execute
    returned_value = self.py_callable(*self.args, **kwargs)
  File "/home/ljcohen/anaconda2/envs/py3.dammit/lib/python3.5/site-packages/shmlast-1.0-py3.5.egg/shmlast/app.py", line 218, in do_crbl_fit_and_filter
    plot_crbh_fit(model_df, hits_df, self.model_plot_fn)
  File "/home/ljcohen/anaconda2/envs/py3.dammit/lib/python3.5/site-packages/shmlast-1.0-py3.5.egg/shmlast/crbl.py", line 131, in plot_crbh_fit
    line_kws=line_kws, color=scatter_kws['c'], ax=ax)
  File "/home/ljcohen/anaconda2/envs/py3.dammit/lib/python3.5/site-packages/seaborn-0.7.1-py3.5.egg/seaborn/linearmodels.py", line 779, in regplot
    plotter.plot(ax, scatter_kws, line_kws)
  File "/home/ljcohen/anaconda2/envs/py3.dammit/lib/python3.5/site-packages/seaborn-0.7.1-py3.5.egg/seaborn/linearmodels.py", line 330, in plot
    self.scatterplot(ax, scatter_kws)
  File "/home/ljcohen/anaconda2/envs/py3.dammit/lib/python3.5/site-packages/seaborn-0.7.1-py3.5.egg/seaborn/linearmodels.py", line 359, in scatterplot
    ax.scatter(x, y, **kws)
  File "/home/ljcohen/anaconda2/envs/py3.dammit/lib/python3.5/site-packages/matplotlib/__init__.py", line 1819, in inner
    return func(ax, *args, **kwargs)
  File "/home/ljcohen/anaconda2/envs/py3.dammit/lib/python3.5/site-packages/matplotlib/axes/_axes.py", line 3789, in scatter
    raise ValueError("Supply a 'c' kwarg or a 'color' kwarg"
ValueError: Supply a 'c' kwarg or a 'color' kwarg but not both; they differ but their functionalities overlap.

**Comment by camillescott** [comment]
This is a bug in matplotlib 1.5.3; i've updated the shmlast install requirements and instructions, which fixes this. Thanks!
