### ISSUE TITLE
Some tasks failed![dammit.annotate:ERROR]

### ISSUE THREAD

**Issue by Reafdaw** [camillescott/dammit#80]
```
 dammit annotate Mspi_normalized_Trinity.fasta --busco-group metazoa --n_threads 36 --database-dir ~/mnt
/dammit/ --full

--- Running annotate!

          Transcriptome file: Mspi_Rcorr_trinity.Trinity.fasta

          Output directory: /home/jeremias/assembly/BSSE_2015.12/khmer_assembly/Mspi_rcorr
          ector/Mspi_Rcorr_trinity.Trinity.fasta.dammit

          [x] Mspi_Rcorr_trinity.Trinity.fasta

          [x] transcriptome_stats:Mspi_Rcorr_trinity.Trinity.fasta

          [x] busco:Mspi_Rcorr_trinity.Trinity.fasta-metazoa

          [x] TransDecoder.LongOrfs:Mspi_Rcorr_trinity.Trinity.fasta

          [x] hmmscan:longest_orfs.pep.x.Pfam-A.hmm

          [x] remap_hmmer:longest_orfs.pep.pfam.tbl

          [x] TransDecoder.Predict:Mspi_Rcorr_trinity.Trinity.fasta

          [ ] cmscan:Mspi_Rcorr_trinity.Trinity.fasta.x.Rfam.cm

          [x] lastal:Mspi_Rcorr_trinity.Trinity.fasta.x.orthodb.maf

          [x] lastal:Mspi_Rcorr_trinity.Trinity.fasta.x.uniref.maf

          [x] maf_best_hits:Mspi_Rcorr_trinity.Trinity.fasta.x.orthodb.maf-
          Mspi_Rcorr_trinity.Trinity.fasta.x.orthodb.maf.best.csv

          [x] maf-gff3:Mspi_Rcorr_trinity.Trinity.fasta.x.orthodb.maf.gff3

          [x] maf_best_hits:Mspi_Rcorr_trinity.Trinity.fasta.x.uniref.maf-
          Mspi_Rcorr_trinity.Trinity.fasta.x.uniref.maf.best.csv

          [x] maf-gff3:Mspi_Rcorr_trinity.Trinity.fasta.x.uniref.maf.best.csv.gff3

          [x] hmmscan-gff3:Mspi_Rcorr_trinity.Trinity.fasta.pfam.csv.gff3

          [ ] cmscan-gff3:Mspi_Rcorr_trinity.Trinity.fasta.rfam.tbl.gff3

          [ ] gff3-merge:Mspi_Rcorr_trinity.Trinity.fasta.dammit.gff3

          [ ] fasta-annotate:Mspi_Rcorr_trinity.Trinity.fasta.dammit.fasta


TaskError - taskid:fasta-annotate:Mspi_normalized_Trinity.fasta.dammit.fasta[dammit.annotate:ERROR]
PythonAction Error
Traceback (most recent call last):
  File "/home/jeremias/.linuxbrew/var/pyenv/versions/anaconda2-4.1.1/lib/python2.7/site-packages/doit/action.py", line 383, in execute
    returned_value = self.py_callable(*self.args, **kwargs)
  File "/home/jeremias/.linuxbrew/var/pyenv/versions/anaconda2-4.1.1/lib/python2.7/site-packages/dammit/tasks.py", line 687, in annotate_fasta
    for _, row in fgroup.iterrows()])
ValueError: cannot convert float NaN to integer
[dammit.annotate:ERROR]

```

**Comment by camillescott** [comment]
Hi @Reafdaw,

This is an error related to a change in pandas behavior between versions 1.8 and 1.9. For now, the fix for dammit 0.3 is to lock in at pandas 1.8.1; the impending dammit 1.0 release address it explicitly. You can install the older version of pandas by either doing:

```
pip install pandas==1.8.1
```

or

```
conda install pandas==1.8.1
```

Cheers,
Camille
