### ISSUE TITLE
Error when annotating sample data

### ISSUE THREAD

**Issue by NBKingsley** [camillescott/dammit#84]
After getting dammit and all of the dependencies installed onto my Ubuntu machine, I tried following the annotation tutorial with the sample data, but the program failed after about  four hours with the following error message:

'''

--- Running annotate!

          Transcriptome file: cdna_nointrons_utrs.fa

          Output directory: /home/nbkingsley/dammit_test/cdna_nointrons_utrs.fa.dammit

          [x] cdna_nointrons_utrs.fa

          [x] transcriptome_stats:cdna_nointrons_utrs.fa

          [x] busco:cdna_nointrons_utrs.fa-eukaryota

          [x] TransDecoder.LongOrfs:cdna_nointrons_utrs.fa

          [ ] hmmscan:longest_orfs.pep.x.Pfam-A.hmm

          [ ] remap_hmmer:longest_orfs.pep.pfam.tbl

          [ ] TransDecoder.Predict:cdna_nointrons_utrs.fa

          [ ] cmscan:cdna_nointrons_utrs.fa.x.Rfam.cm

          [ ] lastal:cdna_nointrons_utrs.fa.x.orthodb.maf

          [ ] sanitize_fasta:pep.fa

          [ ] crb-blast:cdna_nointrons_utrs.fa.x.pep.fa

          [ ] maf_best_hits:cdna_nointrons_utrs.fa.x.orthodb.maf-
          cdna_nointrons_utrs.fa.x.orthodb.maf.best.csv

Some tasks failed![dammit.annotate:ERROR]
TaskError - taskid:maf_best_hits:cdna_nointrons_utrs.fa.x.orthodb.maf-cdna_nointrons_utrs.fa.x.orthodb.maf.best.csv[dammit.annotate:ERROR]
PythonAction Error
Traceback (most recent call last):
  File "/home/nbkingsley/dammitENV/local/lib/python2.7/site-packages/doit/action.py", line 383, in execute
    returned_value = self.py_callable(*self.args, **kwargs)
  File "/home/nbkingsley/dammitENV/local/lib/python2.7/site-packages/dammit/tasks.py", line 327, in cmd
    df = maf.MafParser(maf_fn).read()
  File "/home/nbkingsley/dammitENV/local/lib/python2.7/site-packages/dammit/fileio/maf.py", line 16, in read
    return pd.concat(self, ignore_index=True)
  File "/home/nbkingsley/dammitENV/local/lib/python2.7/site-packages/pandas/tools/merge.py", line 1334, in concat
    copy=copy)
  File "/home/nbkingsley/dammitENV/local/lib/python2.7/site-packages/pandas/tools/merge.py", line 1367, in __init__
    raise ValueError('No objects to concatenate')
ValueError: No objects to concatenate
[dammit.annotate:ERROR]
'''
Any insights as to the cause of this error?

**Comment by AdamStuckert** [comment]
Did you figure this out @NBKingsley ? I'm getting the same error.

**Comment by camillescott** [comment]
I believe the answer was that she is running version 0.3, and that this is fixed in the 1.0 release candidate. There are instructions [here](http://angus.readthedocs.io/en/2017/dammit_annotation.html) for getting that (I need to update the README)

**Comment by AdamStuckert** [comment]
Excellent, that worked. Thanks Camille!
