### ISSUE TITLE
khmer error message during dammit install v1.0

### ISSUE THREAD

**Issue by eeflynn** [camillescott/dammit#89]
Trying to install dammit databases after what appears to be a successful install of the program following instructions http://eel-pond.readthedocs.io/en/latest/5-annotating.html

pip install https://github.com/camillescott/dammit/archive/refactor/1.0.zip

`
Collecting https://github.com/camillescott/dammit/archive/refactor/1.0.zip
  Downloading https://github.com/camillescott/dammit/archive/refactor/1.0.zip
     - 2.1MB 74.3MB/s
Requirement already satisfied: setuptools>=0.6.35 in /home/ubuntu/.local/lib/python3.5/site-packages (from dammit==1.0.dev0)
Requirement already satisfied: pandas>=0.18.1 in /home/ubuntu/anaconda2/envs/dammit/lib/python3.5/site-packages (from dammit==1.0.dev0)
Collecting khmer>=2.0 (from dammit==1.0.dev0)
  Using cached khmer-2.0.tar.gz
Requirement already satisfied: doit>=0.29.0 in /home/ubuntu/anaconda2/envs/dammit/lib/python3.5/site-packages (from dammit==1.0.dev0)
Requirement already satisfied: Sphinx>1.3.1 in /home/ubuntu/anaconda2/envs/dammit/lib/python3.5/site-packages/Sphinx-1.5.1-py3.5.egg (from dammit==1.0.dev0)
Collecting sphinx-rtd-theme>=0.1.9 (from dammit==1.0.dev0)
  Downloading sphinx_rtd_theme-0.1.9-py3-none-any.whl (693kB)
    100% |████████████████████████████████| 696kB 1.9MB/s 
Collecting sphinxcontrib-napoleon>=0.3.11 (from dammit==1.0.dev0)
  Downloading sphinxcontrib_napoleon-0.6.0-py2.py3-none-any.whl
Requirement already satisfied: nose>=1.3.4 in /home/ubuntu/anaconda2/envs/dammit/lib/python3.5/site-packages (from dammit==1.0.dev0)
Requirement already satisfied: nose-capturestderr>=1.0 in /home/ubuntu/anaconda2/envs/dammit/lib/python3.5/site-packages (from dammit==1.0.dev0)
Requirement already satisfied: ficus>=0.1 in /home/ubuntu/anaconda2/envs/dammit/lib/python3.5/site-packages (from dammit==1.0.dev0)
Requirement already satisfied: matplotlib>=1.0 in /home/ubuntu/anaconda2/envs/dammit/lib/python3.5/site-packages (from dammit==1.0.dev0)
Requirement already satisfied: numexpr>=2.3.1 in /home/ubuntu/anaconda2/envs/dammit/lib/python3.5/site-packages (from dammit==1.0.dev0)
Requirement already satisfied: shmlast>=1.0.3 in /home/ubuntu/anaconda2/envs/dammit/lib/python3.5/site-packages (from dammit==1.0.dev0)
Requirement already satisfied: appdirs>=1.4.0 in /home/ubuntu/.local/lib/python3.5/site-packages (from setuptools>=0.6.35->dammit==1.0.dev0)
Requirement already satisfied: packaging>=16.8 in /home/ubuntu/.local/lib/python3.5/site-packages (from setuptools>=0.6.35->dammit==1.0.dev0)
Requirement already satisfied: six>=1.6.0 in /home/ubuntu/.local/lib/python3.5/site-packages (from setuptools>=0.6.35->dammit==1.0.dev0)
Requirement already satisfied: python-dateutil>=2 in /home/ubuntu/anaconda2/envs/dammit/lib/python3.5/site-packages (from pandas>=0.18.1->dammit==1.0.dev0)
Requirement already satisfied: pytz>=2011k in /home/ubuntu/anaconda2/envs/dammit/lib/python3.5/site-packages (from pandas>=0.18.1->dammit==1.0.dev0)
Requirement already satisfied: numpy>=1.7.0 in /home/ubuntu/anaconda2/envs/dammit/lib/python3.5/site-packages (from pandas>=0.18.1->dammit==1.0.dev0)
Requirement already satisfied: screed>=0.9 in /home/ubuntu/anaconda2/envs/dammit/lib/python3.5/site-packages (from khmer>=2.0->dammit==1.0.dev0)
Requirement already satisfied: bz2file in /home/ubuntu/anaconda2/envs/dammit/lib/python3.5/site-packages (from khmer>=2.0->dammit==1.0.dev0)
Requirement already satisfied: cloudpickle in /home/ubuntu/anaconda2/envs/dammit/lib/python3.5/site-packages (from doit>=0.29.0->dammit==1.0.dev0)
Requirement already satisfied: pyinotify in /home/ubuntu/anaconda2/envs/dammit/lib/python3.5/site-packages (from doit>=0.29.0->dammit==1.0.dev0)
Requirement already satisfied: Jinja2>=2.3 in /home/ubuntu/anaconda2/envs/dammit/lib/python3.5/site-packages (from Sphinx>1.3.1->dammit==1.0.dev0)
Requirement already satisfied: Pygments>=2.0 in /home/ubuntu/anaconda2/envs/dammit/lib/python3.5/site-packages (from Sphinx>1.3.1->dammit==1.0.dev0)
Requirement already satisfied: docutils>=0.11 in /home/ubuntu/anaconda2/envs/dammit/lib/python3.5/site-packages (from Sphinx>1.3.1->dammit==1.0.dev0)
Requirement already satisfied: snowballstemmer>=1.1 in /home/ubuntu/anaconda2/envs/dammit/lib/python3.5/site-packages (from Sphinx>1.3.1->dammit==1.0.dev0)
Requirement already satisfied: babel!=2.0,>=1.3 in /home/ubuntu/anaconda2/envs/dammit/lib/python3.5/site-packages (from Sphinx>1.3.1->dammit==1.0.dev0)
Requirement already satisfied: alabaster<0.8,>=0.7 in /home/ubuntu/anaconda2/envs/dammit/lib/python3.5/site-packages (from Sphinx>1.3.1->dammit==1.0.dev0)
Requirement already satisfied: imagesize in /home/ubuntu/anaconda2/envs/dammit/lib/python3.5/site-packages (from Sphinx>1.3.1->dammit==1.0.dev0)
Requirement already satisfied: requests in /home/ubuntu/anaconda2/envs/dammit/lib/python3.5/site-packages (from Sphinx>1.3.1->dammit==1.0.dev0)
Collecting pockets>=0.3 (from sphinxcontrib-napoleon>=0.3.11->dammit==1.0.dev0)
  Downloading pockets-0.3.1-py2.py3-none-any.whl
Requirement already satisfied: cycler in /home/ubuntu/anaconda2/envs/dammit/lib/python3.5/site-packages (from matplotlib>=1.0->dammit==1.0.dev0)
Requirement already satisfied: pyparsing!=2.0.4,>=1.5.6 in /home/ubuntu/.local/lib/python3.5/site-packages (from matplotlib>=1.0->dammit==1.0.dev0)
Requirement already satisfied: seaborn>=0.6.0 in /home/ubuntu/anaconda2/envs/dammit/lib/python3.5/site-packages (from shmlast>=1.0.3->dammit==1.0.dev0)
Requirement already satisfied: filelock>=2.0.6 in /home/ubuntu/anaconda2/envs/dammit/lib/python3.5/site-packages (from shmlast>=1.0.3->dammit==1.0.dev0)
Requirement already satisfied: scipy>=0.16.0 in /home/ubuntu/anaconda2/envs/dammit/lib/python3.5/site-packages (from shmlast>=1.0.3->dammit==1.0.dev0)
Requirement already satisfied: pytest>=2.5 in /home/ubuntu/anaconda2/envs/dammit/lib/python3.5/site-packages (from shmlast>=1.0.3->dammit==1.0.dev0)
Requirement already satisfied: MarkupSafe>=0.23 in /home/ubuntu/anaconda2/envs/dammit/lib/python3.5/site-packages (from Jinja2>=2.3->Sphinx>1.3.1->dammit==1.0.dev0)
Requirement already satisfied: py>=1.4.29 in /home/ubuntu/anaconda2/envs/dammit/lib/python3.5/site-packages (from pytest>=2.5->shmlast>=1.0.3->dammit==1.0.dev0)
Building wheels for collected packages: khmer
  Running setup.py bdist_wheel for khmer ... done
  Stored in directory: /home/ubuntu/.cache/pip/wheels/d0/0f/9a/6294ad563949d6693fee4073b3e4b8840f13ddbcad779920c5
Successfully built khmer
Installing collected packages: khmer, sphinx-rtd-theme, pockets, sphinxcontrib-napoleon, dammit
  Running setup.py install for dammit ... done
Successfully installed dammit-1.0.dev0 khmer-2.0 pockets-0.3.1 sphinx-rtd-theme-0.1.9 sphinxcontrib-napoleon-0.6.0
`

But when I try to install the databases

dammit databases --install

`Traceback (most recent call last):
  File "/home/ubuntu/anaconda2/envs/dammit/bin/dammit", line 5, in <module>
    from dammit import app
  File "/home/ubuntu/anaconda2/envs/dammit/lib/python3.5/site-packages/dammit/app.py", line 13, in <module>
    from . import annotate
  File "/home/ubuntu/anaconda2/envs/dammit/lib/python3.5/site-packages/dammit/annotate.py", line 15, in <module>
    from .tasks.fastx import (get_transcriptome_stats_task,
  File "/home/ubuntu/anaconda2/envs/dammit/lib/python3.5/site-packages/dammit/tasks/fastx.py", line 11, in <module>
    from khmer import HLLCounter, ReadParser
  File "/home/ubuntu/anaconda2/envs/dammit/lib/python3.5/site-packages/khmer/__init__.py", line 42, in <module>
    from khmer._khmer import Countgraph as _Countgraph
ImportError: /home/ubuntu/anaconda2/envs/dammit/lib/python3.5/site-packages/khmer/_khmer.cpython-35m-x86_64-linux-gnu.so: undefined symbol: _ZTVNSt7__cxx1115basic_stringbufIcSt11char_traitsIcESaIcEEE`

Any suggestions? Running Ubuntu 15.10

**Comment by eeflynn** [comment]
Creating a new virtual environment and reinstalling seemed to fix this problem. I had issues with old version of BUSCO causing problems, but after deleting them I was able to get the program to run.
